clusters: 1
partitions: 1
replicas: 1

proxy:
  image:
    repository: atomix/redis-storage-node
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []

backend:
  image:
      repository: redis
      tag: latest
      pullPolicy: IfNotPresent
      pullSecrets: []
